language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_install:
    - pip install poetry
install:
    - poetry install
script:
    - poetry run flake8 .
    # - poetry run mypy src/
    - poetry run pydocstyle src/
    - poetry run pytest tests/
