version: "3"

services:
  gitgetter:
    build: .
    environment:
      - GG_GITHUB_TOKEN
      - GG_SERVER_PORT
    ports:
      - "${GG_SERVER_PORT:-5000}:5000"
    volumes:
      - .:/app
    command: ["python", "-m", "gitgetter"]
